name: refresh

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: 0 0 1
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: refresh
    steps:
      - uses: actions/checkout@latest
      - name: Auto Renew
        env:
          SECRET_FILES: ${{ secrets.SECRET_FILES }}
        run: ./acme-autorenew.sh
