name: refresh

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: 0 0 1
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: refresh
    steps:
      - name: Auto Renew
        env:
          SECRET_FILES: ${{ secrets.SECRET_FILES }}
        run: ls ~ -lah ; ls ~/acme-autorenew.sh -lah; ~/acme-autorenew.sh
